### ISSUE TITLE
在1.3的更新中，svip3转vpr等格式相对音高转化幅度过低。

### ISSUE THREAD

**Issue by FLHUAJI** [SoulMelody/LibreSVIP#482]
感谢开发大大！在近期1.3.0以及1.3.1的版本的相对音高转化更新中，现版本的音高转化修复了原有音高曲线转化幅度大导致割裂的问题，但仍有些不太自然。且在网易云音乐x studio的SVIP3格式转VPR中出现了相对音高转化过低的问题，音高曲线几乎不生效。辛苦大大帮忙看下🥰
![image](https://github.com/user-attachments/assets/99cb78b2-ae91-4c3c-8863-1bd0d248c737)
图1，1.3.1版本转化后vpr工程中的PB
![image](https://github.com/user-attachments/assets/2a1817b3-2d71-439d-a6f9-74afedccbfa3)
图2，1.3.1版本转化后vpr工程中的PBS
![image](https://github.com/user-attachments/assets/f32020e7-a129-44e8-9931-1f94cff6b00f)
图3，转化源文件（.SVIP3）的对应音高参数

**Comment by SoulMelody** [comment]
收到，问题已记录

**Comment by SoulMelody** [comment]
你提到的音高转化幅度过低的问题，在我这里好像没法复现╮(╯▽╰)╭，方便提供一下测试工程吗？

**Comment by FLHUAJI** [comment]
> 你提到的音高转化幅度过低的问题，在我这里好像没法复现╮(╯▽╰)╭，方便提供一下测试工程吗？

[发送.zip](https://github.com/user-attachments/files/17133855/default.zip)
开发大大你好，很抱歉没有及时回复消息＞﹏＜在我最近的使用中发现这个并不是每次都会复现，是偶发性的，可能是bug？这里将出问题的这一份工程文件附在这边，压缩包内有三个文件，一份是SVIP3，另外两份是分别由1.2.4和1.3.1两种版本转换出来的vpr文件，还请查收。这份文件是近期网易云xs创建的文件，有一条轨道洛天依，由内建的人声转midi生成，尚未进行填词，部分音高曲线有修整，总体完成度不高。

**Comment by SoulMelody** [comment]
>
> [发送.zip](https://github.com/user-attachments/files/17133855/default.zip) 开发大大你好，很抱歉没有及时回复消息＞﹏＜在我最近的使用中发现这个并不是每次都会复现，是偶发性的，可能是bug？这里将出问题的这一份工程文件附在这边，压缩包内有三个文件，一份是SVIP3，另外两份是分别由1.2.4和1.3.1两种版本转换出来的vpr文件，还请查收。这份文件是近期网易云xs创建的文件，有一条轨道洛天依，由内建的人声转midi生成，尚未进行填词，部分音高曲线有修整，总体完成度不高。

找到问题了👌，是pbs值越界了导致的

**Comment by SoulMelody** [comment]
此问题已在新发布的 [1.3.2](https://github.com/SoulMelody/LibreSVIP/releases/tag/v1.3.2) 版本中得到解决
