### ISSUE TITLE
Unicode errors keeps CLI from lsiting plugins

### ISSUE THREAD

**Issue by fcnjd** [SoulMelody/LibreSVIP#559]
Hi,
it's me again with one more bug report.
I'm trying to run the plugin list command. This is the output I'm getting:
| No.   | Name          | Version | Author        | Identifier | file format  |
|-------+---------------+---------+---------------+------------+--------------|
| [1]   | ACE Studio    | 0.8.3   | +--------------------- Traceback (most recent call last) ---------------------+
| C:\Users\Fabian\miniconda3\envs\diffsinger\lib\site-packages\libresvip\cli\ |
| commands\plugin.py:44 in list_plugins                                       |
Now some long trace, the final line:
UnicodeEncodeError: 'charmap' codec can't encode characters in position 2-3: 
character maps to <undefined>
I'm using Git bash on Windows 10.

**Comment by SoulMelody** [comment]
I found an answer that may help https://github.com/pypa/pip/issues/11798#issuecomment-1427066597

**Comment by fcnjd** [comment]
Thank you for that hint, yes now it works correctly.
